# Generated by Django 3.1.7 on 2021-03-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NSManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NSShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('RYG', 'ROYGBIV'), ('WH', 'White'), ('BLK', 'Black')], default='WH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NSShoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NSShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, default='', max_length=3)),
                ('brand_name', models.CharField(blank=True, default='', max_length=50)),
                ('material', models.CharField(blank=True, default='', max_length=25)),
                ('fasten_type', models.CharField(blank=True, default='', max_length=25)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutshell_app.nsshoecolor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutshell_app.nsmanufacturer')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutshell_app.nsshoetype')),
            ],
        ),
    ]
