# Generated by Django 3.1.7 on 2021-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutshell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsshoe',
            name='size',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
