# Generated by Django 3.1.7 on 2021-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutshell_app', '0003_auto_20210324_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsmanufacturer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
